rdoc/src/Entity/Account.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AccountRepository")
 */
class Account
{
    public function __construct()
    {
        $this->observations = new ArrayCollection();
        $this->healthObservations = new ArrayCollection();
        $this->consultations = new ArrayCollection();
        $this->runningObservations = new ArrayCollection();

    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $chatbotId;

    /**
     * @ORM\Column(type="string", name="patient_id", length=100, nullable=true)
     */
    private $patientId;

    /**
     * @ORM\Column(type="string", name="patient_global_code", length=100, nullable=true)
     */
    private $patientGlobalCode;

    /**
     * @ORM\Column(type="string", length=100, name="first_name", nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=100, name="last_name", nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=100, name="access_token", nullable=true)
     */
    private $accessToken;

    /**
     * @var \DateTime $tokenLastRefreshedAt
     * @ORM\Column(type="datetime", length=100, name="token_last_refreshed_at", nullable=true)
     */
    private $tokenLastRefreshedAt;

    /**
     * An observation is one that comes from the Orion system.
     * @ORM\OneToMany(targetEntity="App\Entity\Observation", mappedBy="account", orphanRemoval=true)
     */
    private $observations;

    /**
     * A health observation is one made by the app itself, before adding it to Orion.
     * @ORM\OneToMany(targetEntity="App\Entity\HealthObservation", mappedBy="account", orphanRemoval=true)
     */
    private $healthObservations;

    /**
     * A consultation able to be observed by a doctor
     * @ORM\OneToMany(targetEntity="App\Entity\Consultation", mappedBy="account", orphanRemoval=true)
     */
    private $consultations;

    /**
     * @var \DateTime $lastLoginAt
     * @ORM\Column(type="datetime", name="last_login_at", nullable=true)
     */
    private $lastLoginAt;

    /**
     * @ORM\Column(type="decimal", name="latitude", precision=10, scale=6, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="decimal", name="longitude", precision=10, scale=6, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=100, name="city", nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=100, name="country", nullable=true)
     */
    private $country;

    //+44 7373 37373

    /**
     * @ORM\Column(type="string", length=30, name="mobile", nullable=true)
     */
    private $mobile;


    private $runningObservations;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getChatbotId()
    {
        return $this->chatbotId;
    }

    /**
     * @param mixed $chatbotId
     */
    public function setChatbotId($chatbotId)
    {
        $this->chatbotId = $chatbotId;
    }

    /**
     * @return mixed
     */
    public function getPatientId()
    {
        return $this->patientId;
    }

    /**
     * @param mixed $patientId
     */
    public function setPatientId($patientId)
    {
        $this->patientId = $patientId;
    }

    /**
     * @return mixed
     */
    public function getPatientGlobalCode()
    {
        return $this->patientGlobalCode;
    }

    /**
     * @param mixed $patientGlobalCode
     */
    public function setPatientGlobalCode($patientGlobalCode)
    {
        $this->patientGlobalCode = $patientGlobalCode;
    }

    public function getFullName()
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param mixed $firstName
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param mixed $lastName
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
    }

    /**
     * @return mixed
     */
    public function getAccessToken()
    {
        return $this->accessToken;
    }

    /**
     * @param mixed $accessToken
     */
    public function setAccessToken($accessToken)
    {
        $this->accessToken = $accessToken;
    }

    /**
     * @return mixed
     */
    public function getTokenLastRefreshedAt()
    {
        return $this->tokenLastRefreshedAt;
    }

    /**
     * @param mixed $tokenLastRefreshedAt
     */
    public function setTokenLastRefreshedAt($tokenLastRefreshedAt)
    {
        $this->tokenLastRefreshedAt = $tokenLastRefreshedAt;
    }

    public function getTokenIsExpired(\DateTime $currentDateTime)
    {
        if (null == $this->getTokenLastRefreshedAt()) {
            return true;
        } else {
            $tokenLastRefreshedAt = $this->getTokenLastRefreshedAt();
        }

        $interval = $currentDateTime->getTimestamp() - $tokenLastRefreshedAt->getTimestamp();

        $hours = 3;

        $isExpired = ($interval > ($hours * 60 * 60));

        return $isExpired;

    }

    /**
     * @return Collection|Observation
     */
    public function getObservations()
    {
        return $this->observations;
    }

    public function addObservation(Observation $observation)
    {
        if ($this->observations->contains($observation)) {
            return;
        }

        $this->observations[] = $observation;
        $observation->setAccount($this);
    }

    public function removeObservation(Observation $observation)
    {
        $this->observations->removeElement($observation);
        $observation->setAccount(null);
    }

    /**
     * @return mixed
     */
    public function getHealthObservations()
    {
        return $this->healthObservations;
    }

    public function addHealthObservation(HealthObservation $healthObservation)
    {
        if ($this->healthObservations->contains($healthObservation)) {
            return;
        }

        $this->healthObservations[] = $healthObservation;
        $healthObservation->setAccount($this);
    }

    public function removeHealthObservation(HealthObservation $healthObservation)
    {
        $this->healthObservations->removeElement($healthObservation);
        $healthObservation->setAccount(null);
    }

    /**
     * @return mixed
     */
    public function getConsultations()
    {
        return $this->consultations;
    }

    public function addConslutation(Consultation $consultation)
    {
        if ($this->consultations->contains($consultation)) {
            return;
        }

        $this->consultations[] = $consultation;
        $consultation->setAccount($this);
    }

    public function removeConsultation(Consultation $consultation)
    {
        $this->consultations->removeElement($consultation);
        $consultation->setAccount(null);
    }


    /**
     * @return \DateTime
     */
    public function getLastLoginAt()
    {
        return $this->lastLoginAt;
    }

    /**
     * @param \DateTime $lastLoginAt
     */
    public function setLastLoginAt($lastLoginAt)
    {
        $this->lastLoginAt = $lastLoginAt;
    }

    /**
     * @return decimal
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * @param decimal $latitude
     */
    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;
    }

    /**
     * @return decimal
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * @param decimal $longitude
     */
    public function setLongitude($longitude)
    {
        $this->longitude = $longitude;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param string $city
     */
    public function setCity($city)
    {
        $this->city = $city;
    }

    /**
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }

    /**
     * @return mixed
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * @param mixed $mobile
     */
    public function setMobile($mobile)
    {
        $this->mobile = $mobile;
    }


    public function addRunningObservation(RunningObservation $runningObservation)
    {
        if ($this->runningObservations == null) {
            $this->runningObservations = new ArrayCollection();
        }
        if ($this->runningObservations->contains($runningObservation)) {
            return;
        }

        $this->runningObservations[] = $runningObservation;
        $runningObservation->setAccount($this);
    }

    public function setRunningObservations(array $runningObservationsArray)
    {
        foreach ($runningObservationsArray as $runningObservation) {
            $this->addRunningObservation($runningObservation);
        }
    }

    public function getRunningObservations()
    {
        return $this->runningObservations;
    }

    public function getTotalMetersRun()
    {
        $total = 0;
        /**
         * @var RunningObservation $runningObservation
         */

rdoc/src/Controller/DoctorController.php
<?php

namespace App\Controller;

use App\Entity\Account;
use App\Entity\Consultation;
use App\Entity\RunningObservation;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DoctorController extends BaseController
{
    /**
     * @Route("/doctor/account", name="doctor_account")
     */
    public function account(EntityManagerInterface $em)
    {
        return $this->render('Doctor/account.html.twig', [
            'pageName' => 'doctorAccount'
        ]);
    }


    /**
     * @Route("/doctor/resolve-triage", name="doctor_resolve_triage", methods={"POST"})
     */
    public function resolveTriage(Request $request, EntityManagerInterface $em)
    {
        $params = urldecode($request->getContent());
        $keyValues = [];

        foreach (explode('&', $params) as $chunk) {
            $param = explode("=", $chunk);

            if ($param) {
                $keyValues[urldecode($param[0])] = urldecode($param[1]);
            }
        }

        $consultationId = (int)$keyValues['consultation_id'];

        $consultationRepo = $em->getRepository(Consultation::class);
        /**
         * @var Consultation $consultation
         */
        $consultation = $consultationRepo->find($consultationId);

        if (null == $consultation) {
            return new JsonResponse(array('success' => false, 'message' => 'Consultation was not found'));
        }

        $consultation->setIsPending(false);
        $em->persist($consultation);
        $em->flush();

        return new JsonResponse(array('success' => true));
    }

    /**
     * @Route("/doctor/deploy-drone", name="doctor_deploy_drone", methods={"POST"})
     */
    public function deployDrone(Request $request, EntityManagerInterface $em, \Swift_Mailer $mailer)
    {
        $params = urldecode($request->getContent());
        $keyValues = [];

        foreach (explode('&', $params) as $chunk) {
            $param = explode("=", $chunk);

            if ($param) {
                $keyValues[urldecode($param[0])] = urldecode($param[1]);
            }
        }

        $accountNum = (int)$keyValues['account_id'];
        if ($accountNum > 0) {
            $accountRepo = $em->getRepository(Account::class);
            $account = $accountRepo->find($accountNum);
        } else {
            $account = $this->getAccount($em);
        }

        //make the CSV for the warehouse.


        $fileFullPath = $this->makeCsvForDroneDelivery($account);

        $attachment = \Swift_Attachment::fromPath($fileFullPath);
        $attachment->setFilename('Chat_Bot_Subscription_' . $keyValues['consultation_id'] . '.csv');


        try {

            //using app password for chatdoc: https://myaccount.google.com/u/1/apppasswords
            $message = (new \Swift_Message('Drone Delivery for Perscription '.$keyValues['consultation_id']))
                ->setFrom('nathanlon@gmail.com')
                ->setTo($this->getParameter('warehouse_email'))
                ->setBody(
                    $this->renderView(
                        'Doctor/emails/droneDelivery.html.twig',
                        array_merge(array(
                            'account' => $account,
                        ), $keyValues)
                    ),
                    'text/html'
                )
                ->attach($attachment)
            ;

            $mailer->send($message);
        } catch(\Exception $e) {
            return new JsonResponse(array('success' => false, 'message' => $e->getMessage()));
        }

        return new JsonResponse(array('success' => false));
    }


    private function makeCsvForDroneDelivery(Account $account, $warehouseLat = null, $warehouseLng = null)
    {
        if ((null == $warehouseLat) || (null == $warehouseLng)) {
            $warehouseLat = $this->getParameter('warehouse_latitude');
            $warehouseLng = $this->getParameter('warehouse_longitude');
        }

        $csvOutput = $this->renderView('Doctor/emails/csvForDroneDeploy.csv.twig', array(
            'warehouseLat' => $warehouseLat,
            'warehouseLng' => $warehouseLng,
            'account' => $account
        ));
        $fileName = $account->getId() . '-' . time() . '.csv';

        $fileFullPath = dirname(__FILE__) . '/../../assets/csv/'. $fileName;
        file_put_contents($fileFullPath, $csvOutput);

        return $fileFullPath;
    }

        /**
     * @Route("/doctor/login", name="doctor_login")
     */
    public function logout(EntityManagerInterface $em, \Swift_Mailer $mailer)
    {

        return $this->render('Doctor/login.html.twig', [
            'pageName' => 'doctorLogin'
        ]);
    }

    /**
     * @Route("/doctor", name="doctor")
     */
    public function index(EntityManagerInterface $em)
    {
        $consultationRepo = $em->getRepository(Consultation::class);
        $consultations =  $consultationRepo->findAllPending();

        return $this->render('Doctor/index.html.twig', [
            'pageName' => 'doctor',
            'consultations' => $consultations
        ]);
    }


    /**
     * @Route("/doctor/patient-search", name="doctor_patient_search")
     */
    public function patientSearch(EntityManagerInterface $em, Request $request)
    {
        $accountRepo = $em->getRepository(Account::class);
        //$accounts =  $accountRepo->findAll();

        $q = $request->get('q');

        $accountRepo = $em->getRepository(Account::class);
        $accounts = $accountRepo->searchByLastName($q);

        $runningObRepo = $em->getRepository(RunningObservation::class);

        $accountsWithHealth = array();
        foreach ($accounts as $account) {

            $runningObs = $runningObRepo->findBy(array('account' => $account));
            $account->setRunningObservations($runningObs);

            $accountsWithHealth[] = $account;
        }

        return $this->render('Doctor/patientSearch.html.twig', [
            'pageName' => 'patientSearch',
            'patients' => $accountsWithHealth,
            'q' => $q
        ]);
    }


    /**
     * @Route("/doctor/trends", name="doctor_trends")
     */
    public function trends(EntityManagerInterface $em)
    {

        return $this->render('Doctor/trends.html.twig', [
            'pageName' => 'trends'
        ]);
    }
}

rdoc/templates/Doctor/index/_consultation.html.twig
{% include 'Doctor/index/_modal.html.twig' with {'consultation': consultation } %}
{% include 'Doctor/index/_modalDelivery.html.twig' with {'consultation': consultation } %}


<div class="consultation">

    <div class="row">
        <div class="col col-md-3 summary">
            <h4>{{ consultation.account.fullName }}</h4>
            <div class="lastLogin">{{ consultation.account.lastLoginAt|date }}</div>
            <div class="location">{{ consultation.account.city }}, {{ consultation.account.country }}</div>
        </div>
        <div class="col col-md-9">

            <div id="accordion{{ consultation.id }}" class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion{{ consultation.id }}" href="#collapseOne{{ consultation.id }}">Photo submitted ({{ random(6) }} minutes ago)</a>
                        </h4>
                    </div>
                    <div id="collapseOne{{ consultation.id }}" class="panel-collapse collapse in" style="min-height: 337px;">
                        <div class="panel-body">

                            <div class="taskDescription">
                                Please observe this photo of this condition
                            </div>

                            <div class="doctorActionButtons">
                                <button class="btn btn-default admit">Refer to hospital</button>
                                <button class="btn btn-default send" id="sendItem{{ consultation.id }}" data-toggle="modal" data-target="#modalDelivery{{ consultation.id }}">Send prescription</button>
                                <button class="btn btn-default ask">Begin chatting</button>
                                <button class="btn btn-default call">Phone patient</button>
                                <button class="btn btn-default call resolveTriage" data-cid="{{ consultation.id }}">Triage resolved</button>
                            </div>

                            <div class="bg-success" id="droneDeployedNote{{ consultation.id }}" style="display:none; position: absolute;top: 313px;left: 61px;width: 341px;padding: 5px;">Drone is being prepared for deployment, and prescription is on the way</div>
                            <div class="bg-danger" id="droneDeployedNote{{ consultation.id }}Failed" style="display:none; position: absolute;top: 313px;left: 61px;width: 341px;padding: 5px;">There was a failure sending the notification to the warehouse, please try again.</div>

                            <a type="button" data-toggle="modal" data-target="#modal{{ consultation.id }}" class="expand"><i class="fa fa-expand"></i><span>Full screen</span></a>

                            <a href="{{ path('doctor_patient_search') }}?q={{ consultation.account.lastName }}" class="patientSearch">Patient Health Observations</a>

                            <img  data-toggle="modal" data-target="#modal{{ consultation.id }}"  class="uploadImage" src="/uploads/{{ consultation.imageId }}.jpg" />

                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion{{ consultation.id }}" href="#collapseTwo{{ consultation.id }}">Symptom: {{ consultation.symptom }}</a>
                        </h4>
                    </div>
                    <div id="collapseTwo{{ consultation.id }}" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p>This rash has been looked at by Watson AI, and seems as discribed by the patient.</p>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion{{ consultation.id }}" href="#collapseThree{{ consultation.id }}">Date details: First noticed: {{ consultation.firstNoticedAt|date('d M Y') }}</a>
                        </h4>
                    </div>
                    <div id="collapseThree{{ consultation.id }}" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p>The patient has had good health over the last year with 2 admissions and 220 observations of healthy living.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

rdoc/templates/Doctor/index/_modal.html.twig
<!-- Modal -->
<div class="modal fade" id="modal{{ consultation.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel{{ consultation.id }}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel{{ consultation.id }}">Modal title {{ consultation.id }}</h4>
            </div>
            <div class="modal-body">
                <img class="uploadImageLarge" src="/uploads/{{ consultation.imageId }}.jpg" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                {#<button type="button" class="btn btn-primary">Save changes</button>#}
            </div>
        </div>
    </div>
</div>

rdoc/templates/Doctor/index/_modalDelivery.html.twig
<!-- Modal -->
<div class="modal fade" id="modalDelivery{{ consultation.id }}" tabindex="-1" role="dialog" aria-labelledby="deliveryModalLabel{{ consultation.id }}">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="deliveryModalLabel{{ consultation.id }}">Drone Delivery to {{ consultation.account.fullName }}</h4>
            </div>
            <div class="modal-body">
                <form class="deployDroneForm">
                    <div class="form-group">
                        <label for="deliveryItem{{ consultation.id }}">Item to deliver</label>

                        <select class="form-control" name="medication">
                            <option value="Papulosquamous rash ointment">Papulosquamous rash ointment</option>
                            <option value="Eczematous rash ointment">Eczematous rash ointment</option>
                            <option value="Papular rash ointment">Papular rash ointment</option>
                            <option value="Pustular rash ointment">Pustular rash ointment</option>
                            <option value="Vesiculobullous rash ointment">Vesiculobullous rash ointment</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="deliveryLabel" for="deliveryLatitude{{ consultation.id }}">Latitude</label>
                        <input type="text" name="latitude" id="deliveryLatitude{{ consultation.id }}" value="{{ consultation.account.latitude }}" />
                    </div>
                    <div class="form-group">
                        <label class="deliveryLabel" for="deliveryLongitude{{ consultation.id }}">Longitude</label>
                        <input type="text" name="longitude" id="deliveryLongitude{{ consultation.id }}" value="{{ consultation.account.longitude }}" />
                    </div>
                    <input type="hidden" name="account_id" id="deliveryAccountId{{ consultation.id }}" value="{{ consultation.account.id }}" />
                    <input type="hidden" name="consultation_id" class="consultationId" value="{{ consultation.id }}" />
                    <button type="button" id="droneDeliveryButton{{ consultation.id }}" class="btn btn-primary droneDeliveryButton" data-dismiss="modal">Deliver via Drone</button>
                </form>

                <div class="deliveryMap" id="map{{ consultation.id }}"></div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                {#<button type="button" class="btn btn-primary">Save changes</button>#}
            </div>
        </div>
    </div>
</div>

<script>

    function initMap{{ consultation.id }}() {
        var uluru = {lat: {{ consultation.account.latitude }}, lng: {{ consultation.account.longitude }}};
        var map, infoWindow, watchId, oldPos;
        map = new google.maps.Map(document.getElementById('map{{ consultation.id }}'), {
            zoom: 16,
            center: uluru
        });

        var marker = new google.maps.Marker({
            position: uluru,
            map: map,
            title: '{{ consultation.account.fullName }}'
        });

    }

</script>